import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  Brain, 
  CheckCircle2, 
  HelpCircle, 
  Star, 
  MessageSquare, 
  Plus, 
  Sparkles, 
  Lightbulb,
  Filter,
  Check,
  RotateCw,
  Trash2
} from "lucide-react";

interface Candidate {
  resumeId: string;
  candidateName: string;
  overallScore: number;
  skillsDetected?: string[];
  interviewQuestions?: string[];
}

interface AIInsightsPanelProps {
  candidate: Candidate | null;
}

interface ChecklistItem {
  id: string;
  question: string;
  skill?: string;
  isAsked: boolean;
  rating: number; // 0 to 5
  notes: string;
  isCustom?: boolean;
}

// Built-in map of high-fidelity, skill-specific questions to enrich the checklist dynamically
const SKILL_QUESTION_BANK: { [key: string]: string } = {
  "react": "Describe how you coordinate state management across massive component trees without triggering excessive re-renders.",
  "typescript": "In your work, how do you manage Type definitions and compile-time safety inside high-scale TypeScript systems?",
  "node.js": "How do you handle clustering or cluster-based scaling for Node.js workloads under extremely high concurrent load?",
  "express": "What security headers (e.g., Helmet) and middleware strategies do you implement to safeguard an Express-based REST API?",
  "docker": "Explain the security and size benefits of multi-stage Docker builds compared to standard single-stage builds.",
  "postgresql": "What is the difference between connection pooling and raw client connections in PostgreSQL, and when would you use pgBouncer?",
  "python": "Explain how memory management and the GIL affect concurrent performance in multi-threaded Python applications.",
  "pytorch": "What are the common strategies for debugging gradient vanishing or explosion issues in deep neural networks?",
  "llms": "How do you address prompt injection risks and secure user inputs when using RAG architectures?",
  "kubernetes": "What is the difference between Liveness and Readiness probes in Kubernetes, and how do they impact rolling updates?",
  "fastapi": "How does FastAPI leverage Python's async/await structure under the hood to achieve NodeJS-like execution speeds?",
  "aws": "Explain the difference between IAM roles and IAM users, and describe how you would design a secure, least-privilege cloud bucket policy."
};

export default function AIInsightsPanel({ candidate }: AIInsightsPanelProps) {
  const [checklist, setChecklist] = useState<ChecklistItem[]>([]);
  const [selectedFilter, setSelectedFilter] = useState<string | null>(null);
  const [customQuestionInput, setCustomQuestionInput] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [autoSaveStatus, setAutoSaveStatus] = useState<"saved" | "saving" | null>("saved");

  // Load or generate checklist on candidate change
  useEffect(() => {
    if (!candidate) {
      setChecklist([]);
      setSelectedFilter(null);
      return;
    }

    const storageKey = `recruitmatch_checklist_${candidate.resumeId}`;
    const saved = localStorage.getItem(storageKey);

    if (saved) {
      try {
        setChecklist(JSON.parse(saved));
      } catch (e) {
        console.error("Failed to parse saved checklist:", e);
        generateFreshChecklist();
      }
    } else {
      generateFreshChecklist();
    }
    
    // Reset filter
    setSelectedFilter(null);
  }, [candidate]);

  // Save checklist helper
  const saveChecklist = (updatedList: ChecklistItem[]) => {
    if (!candidate) return;
    setAutoSaveStatus("saving");
    const storageKey = `recruitmatch_checklist_${candidate.resumeId}`;
    localStorage.setItem(storageKey, JSON.stringify(updatedList));
    setTimeout(() => {
      setAutoSaveStatus("saved");
    }, 400);
  };

  const generateFreshChecklist = () => {
    if (!candidate) return;

    const items: ChecklistItem[] = [];
    const baseQuestions = candidate.interviewQuestions || [];

    // 1. Add questions generated by Gemini
    baseQuestions.forEach((q, idx) => {
      items.push({
        id: `gemini-${idx}`,
        question: q,
        isAsked: false,
        rating: 0,
        notes: "",
        skill: "Core Fit"
      });
    });

    // 2. Add skill-specific questions dynamically
    const skills = candidate.skillsDetected || [];
    skills.forEach((skill) => {
      const normalized = skill.toLowerCase();
      if (SKILL_QUESTION_BANK[normalized]) {
        // Prevent duplicate questions
        if (!items.some(item => item.question === SKILL_QUESTION_BANK[normalized])) {
          items.push({
            id: `skill-${normalized}`,
            question: SKILL_QUESTION_BANK[normalized],
            isAsked: false,
            rating: 0,
            notes: "",
            skill: skill
          });
        }
      }
    });

    // 3. Fallbacks if we still have too few questions
    if (items.length < 3) {
      items.push({
        id: "fallback-1",
        question: "Can you detail a high-stress technical failure you experienced and how you systematically debugged it?",
        isAsked: false,
        rating: 0,
        notes: "",
        skill: "Behavioral"
      });
      items.push({
        id: "fallback-2",
        question: "What is your typical approach to code reviews and balancing speed with high software engineering standards?",
        isAsked: false,
        rating: 0,
        notes: "",
        skill: "Leadership"
      });
    }

    setChecklist(items);
    saveChecklist(items);
  };

  // Toggle asked state
  const handleToggleAsked = (id: string) => {
    const updated = checklist.map(item => 
      item.id === id ? { ...item, isAsked: !item.isAsked } : item
    );
    setChecklist(updated);
    saveChecklist(updated);
  };

  // Update rating
  const handleRate = (id: string, rating: number) => {
    const updated = checklist.map(item => 
      item.id === id ? { ...item, rating } : item
    );
    setChecklist(updated);
    saveChecklist(updated);
  };

  // Update notes
  const handleUpdateNotes = (id: string, notes: string) => {
    const updated = checklist.map(item => 
      item.id === id ? { ...item, notes } : item
    );
    setChecklist(updated);
    saveChecklist(updated);
  };

  // Add custom question
  const handleAddCustomQuestion = (e: React.FormEvent) => {
    e.preventDefault();
    if (!customQuestionInput.trim() || !candidate) return;

    setIsGenerating(true);

    // Simulate elite AI question synthesis matching candidate context
    setTimeout(() => {
      const newQuestion: ChecklistItem = {
        id: `custom-${Date.now()}`,
        question: customQuestionInput.trim().endsWith("?") 
          ? customQuestionInput.trim() 
          : `${customQuestionInput.trim()}?`,
        isAsked: false,
        rating: 0,
        notes: "",
        skill: "Custom Focus",
        isCustom: true
      };

      const updated = [...checklist, newQuestion];
      setChecklist(updated);
      saveChecklist(updated);
      setCustomQuestionInput("");
      setIsGenerating(false);
    }, 1200);
  };

  // Remove question
  const handleDeleteQuestion = (id: string) => {
    const updated = checklist.filter(item => item.id !== id);
    setChecklist(updated);
    saveChecklist(updated);
  };

  // Get skills available for filtering
  const availableSkills = candidate ? ["All", ...new Set(checklist.map(item => item.skill).filter(Boolean) as string[])] : [];

  const filteredChecklist = selectedFilter && selectedFilter !== "All"
    ? checklist.filter(item => item.skill === selectedFilter)
    : checklist;

  if (!candidate) {
    return (
      <div className="bg-slate-900/40 p-6 rounded-2xl border border-slate-800/80 text-center text-slate-500 text-xs py-10 font-medium">
        Select a candidate to load their AI Insights Interview Questions Panel.
      </div>
    );
  }

  // Calculate asked progress
  const askedCount = checklist.filter(item => item.isAsked).length;
  const progressPercent = checklist.length > 0 ? Math.round((askedCount / checklist.length) * 100) : 0;

  return (
    <motion.div 
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-slate-900/40 p-6 rounded-2xl border border-slate-800/80 space-y-6 relative overflow-hidden"
    >
      {/* Visual background ambient glow */}
      <div className="absolute -bottom-10 -left-10 h-36 w-36 bg-teal-500/5 rounded-full blur-3xl pointer-events-none" />

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-850 pb-4">
        <div className="flex items-center gap-2.5">
          <div className="p-2 bg-teal-500/10 text-teal-400 rounded-xl border border-teal-500/20">
            <Brain className="h-5 w-5 animate-pulse" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-slate-100 flex items-center gap-1.5">
              AI Insights: Smart Interview Checklist
              <span className="px-2 py-0.5 text-[9px] bg-teal-500/10 text-teal-400 border border-teal-500/20 rounded font-mono font-bold uppercase">
                Dynamic Engine
              </span>
            </h4>
            <p className="text-xs text-slate-400 font-medium mt-0.5">
              Tailored candidate evaluations and tech-stack checks for <span className="text-slate-200 font-bold">{candidate.candidateName}</span>.
            </p>
          </div>
        </div>

        {/* Sync Status / Reset Buttons */}
        <div className="flex items-center gap-3">
          <span className="text-[10px] font-mono text-slate-500 flex items-center gap-1">
            <span className={`h-1.5 w-1.5 rounded-full ${autoSaveStatus === 'saving' ? 'bg-amber-400 animate-pulse' : 'bg-emerald-400'}`} />
            {autoSaveStatus === 'saving' ? 'Saving feedback...' : 'AI Auto-Saved'}
          </span>
          <button 
            onClick={generateFreshChecklist}
            className="p-1.5 hover:bg-slate-950 border border-slate-850 hover:border-slate-800 text-slate-400 hover:text-teal-400 rounded-lg transition text-xs flex items-center gap-1 font-mono cursor-pointer"
            title="Regenerate default questions checklist"
          >
            <RotateCw className="h-3 w-3" />
            Reset
          </button>
        </div>
      </div>

      {/* Progress & Overview */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-4 items-center bg-slate-950/40 p-4 rounded-xl border border-slate-850/80">
        <div className="md:col-span-4 text-center md:text-left space-y-1">
          <span className="text-[9px] text-slate-500 uppercase tracking-wider font-bold">Interview Quality Progress</span>
          <div className="text-xl font-black text-slate-100 font-mono">
            {askedCount} <span className="text-xs text-slate-500">/ {checklist.length} Questions Asked</span>
          </div>
        </div>
        <div className="md:col-span-8">
          <div className="relative pt-1">
            <div className="flex justify-between items-center text-[10px] text-slate-400 font-medium mb-1">
              <span>Completion Index</span>
              <span className="text-teal-400 font-bold font-mono">{progressPercent}%</span>
            </div>
            <div className="h-2 w-full bg-slate-900 rounded-full overflow-hidden border border-slate-850 relative">
              <motion.div 
                className="h-full bg-gradient-to-r from-teal-500 to-emerald-400 rounded-full"
                initial={{ width: 0 }}
                animate={{ width: `${progressPercent}%` }}
                transition={{ duration: 0.8, ease: "easeOut" }}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Skill Filters */}
      {availableSkills.length > 2 && (
        <div className="space-y-1.5">
          <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1">
            <Filter className="h-3 w-3 text-slate-500" /> Filter Checklist by Skill focus
          </span>
          <div className="flex flex-wrap gap-1.5">
            {availableSkills.map((skill, idx) => {
              const isSelected = selectedFilter === skill || (skill === "All" && !selectedFilter);
              return (
                <button
                  key={idx}
                  onClick={() => setSelectedFilter(skill === "All" ? null : skill)}
                  className={`px-2.5 py-1 text-[11px] font-semibold rounded-lg transition cursor-pointer border ${
                    isSelected 
                      ? "bg-teal-500/10 text-teal-400 border-teal-500/20" 
                      : "bg-slate-950/40 text-slate-400 border-slate-850 hover:text-slate-300 hover:border-slate-800"
                  }`}
                >
                  {skill}
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Question Checklist Items */}
      <div className="space-y-3.5">
        <AnimatePresence mode="popLayout">
          {filteredChecklist.map((item, index) => (
            <motion.div
              key={item.id}
              layout
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className={`p-4 rounded-xl border transition ${
                item.isAsked 
                  ? "bg-slate-950/20 border-slate-850/60 opacity-75" 
                  : "bg-slate-950/50 border-slate-850 hover:border-slate-800"
              }`}
            >
              <div className="flex items-start gap-3">
                {/* Custom Styled Checkbox */}
                <button
                  onClick={() => handleToggleAsked(item.id)}
                  className={`mt-0.5 h-4.5 w-4.5 rounded-md flex items-center justify-center transition border cursor-pointer shrink-0 ${
                    item.isAsked 
                      ? "bg-teal-500/20 border-teal-500/40 text-teal-400" 
                      : "bg-slate-900 border-slate-800 hover:border-slate-700 text-transparent"
                  }`}
                >
                  <Check className="h-3 w-3 stroke-[3]" />
                </button>

                <div className="space-y-3 flex-1 min-w-0">
                  {/* Question and Badges */}
                  <div>
                    <div className="flex flex-wrap items-center gap-2 mb-1">
                      {item.skill && (
                        <span className="text-[9px] font-mono font-bold uppercase tracking-wider px-1.5 py-0.5 bg-slate-900 text-slate-400 border border-slate-850 rounded">
                          {item.skill}
                        </span>
                      )}
                      {item.isCustom && (
                        <span className="text-[9px] font-mono font-bold uppercase tracking-wider px-1.5 py-0.5 bg-purple-500/10 text-purple-400 border border-purple-500/25 rounded flex items-center gap-0.5">
                          <Sparkles className="h-2 w-2" /> Custom
                        </span>
                      )}
                    </div>
                    <p className={`text-xs text-slate-100 font-semibold leading-relaxed ${item.isAsked ? 'line-through text-slate-500' : ''}`}>
                      {item.question}
                    </p>
                  </div>

                  {/* Evaluation Actions (Star rating & Notes) */}
                  <div className="grid grid-cols-1 md:grid-cols-12 gap-3.5 pt-3.5 border-t border-slate-900">
                    {/* Interactive Star Rating */}
                    <div className="md:col-span-5 space-y-1">
                      <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider block">Candidate Response Score</span>
                      <div className="flex items-center gap-1">
                        {[1, 2, 3, 4, 5].map((starValue) => {
                          const isActive = item.rating >= starValue;
                          return (
                            <button
                              key={starValue}
                              type="button"
                              onClick={() => handleRate(item.id, starValue)}
                              className="p-0.5 hover:scale-110 transition cursor-pointer text-slate-500 hover:text-teal-400"
                              title={`Rate ${starValue} / 5`}
                            >
                              <Star 
                                className={`h-4 w-4 ${
                                  isActive 
                                    ? "text-teal-400 fill-teal-400/30 filter drop-shadow-[0_0_4px_rgba(20,184,166,0.2)]" 
                                    : "text-slate-700 hover:text-teal-400"
                                }`} 
                              />
                            </button>
                          );
                        })}
                        {item.rating > 0 && (
                          <span className="text-[10px] font-mono font-black text-teal-400 ml-1">
                            {item.rating}.0 / 5
                          </span>
                        )}
                      </div>
                    </div>

                    {/* Interview Notes text area */}
                    <div className="md:col-span-7 space-y-1 relative">
                      <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider block flex items-center gap-1">
                        <MessageSquare className="h-2.5 w-2.5" /> Recruiter Evaluation Notes
                      </span>
                      <input
                        type="text"
                        placeholder="Add quick answers review, tags, or evaluation notes..."
                        value={item.notes}
                        onChange={(e) => handleUpdateNotes(item.id, e.target.value)}
                        className="w-full bg-slate-900 border border-slate-850 hover:border-slate-800 focus:border-teal-500 text-slate-300 text-[11px] rounded-lg px-2.5 py-1 focus:outline-none transition font-medium"
                      />
                    </div>
                  </div>
                </div>

                {/* Delete custom/standard question button */}
                <button
                  onClick={() => handleDeleteQuestion(item.id)}
                  className="p-1 hover:bg-rose-500/10 text-slate-600 hover:text-rose-400 rounded-lg transition self-start cursor-pointer"
                  title="Remove question from interview plan"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                </button>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {filteredChecklist.length === 0 && (
          <div className="text-center py-6 text-slate-500 text-xs font-medium border border-dashed border-slate-850 rounded-xl bg-slate-950/20">
            No questions match the selected filter.
          </div>
        )}
      </div>

      {/* Add Custom Question Form */}
      <form onSubmit={handleAddCustomQuestion} className="bg-slate-950/40 p-4 rounded-xl border border-slate-850/80 space-y-2.5">
        <h5 className="text-[10px] font-bold text-teal-400 uppercase tracking-wider flex items-center gap-1">
          <Lightbulb className="h-3.5 w-3.5 text-teal-400" /> Synthesize a Custom Interview Topic
        </h5>
        <div className="flex gap-2.5">
          <input
            type="text"
            required
            disabled={isGenerating}
            placeholder="Type a custom skill or interview focus (e.g. System Design, GraphQL API)..."
            value={customQuestionInput}
            onChange={(e) => setCustomQuestionInput(e.target.value)}
            className="flex-1 bg-slate-900 border border-slate-850 rounded-xl px-3.5 py-2 text-slate-200 text-xs focus:outline-none focus:border-teal-500 transition font-medium disabled:opacity-50"
          />
          <button
            type="submit"
            disabled={isGenerating || !customQuestionInput.trim()}
            className="px-4 py-2 bg-teal-500 hover:bg-teal-400 text-slate-950 font-black text-xs uppercase tracking-wider rounded-xl transition flex items-center gap-1.5 disabled:opacity-40 cursor-pointer h-9"
          >
            {isGenerating ? (
              <span className="h-3.5 w-3.5 border-2 border-slate-950/30 border-t-slate-950 rounded-full animate-spin" />
            ) : (
              <Plus className="h-3.5 w-3.5" />
            )}
            <span>{isGenerating ? "Synthesizing..." : "Add"}</span>
          </button>
        </div>
      </form>
    </motion.div>
  );
}
